### ISSUE TITLE
l10n French

### ISSUE THREAD

**Issue by trebmuh** [dagargo/microdude#7]
Hi @dagargo 
I'd be glad to provide a French translation for microdude. Unfortunately, I'm unable to do the i18n step. Would you be interested in doing so?

**Comment by dagargo** [comment]
It definitely sounds like a nice addition.
I'll try to do it during the holidays.

**Comment by trebmuh** [comment]
Nice. Feel free to ping me when it's ready for me to start the translation.

Nice end of year to you and yours.

**Comment by dagargo** [comment]
Hi @trebmuh !

I've just created the branch l10n to support localization.
Take a look to the README.md to add a file for French translations.

Thanks for contributing!

**Comment by trebmuh** [comment]
Hi @dagargo , initial French translation done in #8 
I didn't tested it yet, just translated through the github interface.
HTH

**Comment by dagargo** [comment]
I have just accepted your PR and tested it. Looks right to me.
It'd be nice if you could test it too.

**Comment by trebmuh** [comment]
I don't have a micro-brute, but @erwan35 does! Erwan, do you have a bit of time for that?

**Comment by dagargo** [comment]
Hi @trebmuh!

Since I want to release a new version including the localizations, I've just tested the changes on several computers and they all seem to work properly.

Closing the issue as solved.

Thanks for your contribution!

**Comment by dagargo** [comment]
Hi @trebmuh!

I have added pitch and mod wheel calibration and also an option to make changes non persistent (use of MIDI controllers instead of SysEx messages).

Could you, please, add the french translations for the new labels? (The po file already contains the new labels.)

Thanks in advance!

**Comment by trebmuh** [comment]
@dagargo : done in #9

**Comment by dagargo** [comment]
Great!

Thanks for contributing!
